---
collections:
  - name: community.general
    version: 12.2.0
  - name: community.sops
    version: 2.2.7
  - name: ansible.posix
    version: 2.1.0
  - name: kubernetes.core
    version: 6.2.0    
roles:
  - src: xanmanning.k3s
    version: v3.6.2
